import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from 'next/font/google';
import {Toaster} from "@/components/ui/toaster";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '700'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={'dark'}>
      <body
        className={`${roboto.variable} antialiased bg-background`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
